global:
  scrape_interval: 10s

scrape_configs:
  - job_name: "spring-boot-server"
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["3.39.237.240:8080"]

  - job_name: "node-exporter"
    static_configs:
      - targets: ["3.37.207.64:9100"]