name: CD

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: SSH Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          ref: main
          host: ${{ secrets.SSH_HOST }}
          username: ec2-user # EC2 인스턴스 사용자 이름
          key: ${{ secrets.SSH_KEY }}
          script: |
            echo "Starting deployment..."
            docker pull ${{ secrets.AWS_REGISTRY }}:${{ github.sha::8 }}    # Docker 이미지 pull
            docker stop ticketable_web || true   # 이전 컨테이너 중지 및 제거
            docker rm ticketable_web || true
            docker run -d --name ticketable_web -p 80:80 ${{ secrets.AWS_REGISTRY }}/repo-tiketable:${{ github.sha::8 }}    # 새 컨테이너 실행
            echo "Deployment successful!"