# CI : PR이 열리거나 업데이트될 때 테스트와 빌드 수행
name: CI

# develop 또는 main 브랜치로 PR이 열리거나 업데이트될 때 실행
on:
  pull_request:
    branches: ["develop", "main"]
    types: [opened, synchronized]    # PR이 열렸을 때와 코드가 업데이트 되었을 때 실행

# CI 작업 정의
jobs:
  build:
    runs-on: ubuntu-latest    # Ubuntu 최신 버전에서 실행
    steps:
      # 체크 아웃
      - name: Check out
        uses: actions/checkout@v4

      # JDK 17 환경 설정 (corretto 사용)
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'corretto'

      # Gradle wrapper 실행 권한 부여
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      # H2로 테스트 실행 및 빌드
      - name: build with Gradle (H2 Tests)
        run: ./gradlew build